In [2]:
import numpy as np
import pandas as pd

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer

In [4]:
df = pd.read_csv("/content/train.csv" , usecols=['Age','Fare','Survived' ,'Parch','SibSp'])

In [5]:
df.dropna(inplace = True)

In [6]:
df['Family'] = df['SibSp'] + df['Parch']

In [7]:
df.head()

   Survived   Age  SibSp  Parch     Fare  Family
0         0  22.0      1      0   7.2500       1
1         1  38.0      1      0  71.2833       1
2         1  26.0      0      0   7.9250       0
3         1  35.0      1      0  53.1000       1
4         0  35.0      0      0   8.0500       0

In [8]:
df.drop(columns=['SibSp','Parch'] , inplace = True)

In [9]:
df.head()

   Survived   Age     Fare  Family
0         0  22.0   7.2500       1
1         1  38.0  71.2833       1
2         1  26.0   7.9250       0
3         1  35.0  53.1000       1
4         0  35.0   8.0500       0

In [10]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [12]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size =0.2 , random_state = 42)

In [13]:
clf = DecisionTreeClassifier()
clf.fit(X_train , y_train)
y_pred= clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.6433566433566433

In [14]:
#we are using binarizer to figure out if the passanger is travelling alone or not - basically the value of mily column = 0
from sklearn.preprocessing import Binarizer

In [15]:
trf = ColumnTransformer([
    ('bin' , Binarizer(copy = False),['Family'])
], remainder = 'passthrough')

In [16]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [17]:
pd.DataFrame(X_train_trf, columns =['Family' ,'Age','Fare'])

     Family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]